name: social_media_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  build_runner: ^2.4.9
  cloud_firestore: ^4.17.2
  contained_tab_bar_view_with_custom_page_navigator: ^0.1.3
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dynamic_tabbar: ^1.0.7
  equatable: ^2.0.5
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  firebase_crashlytics: ^3.5.1
  firebase_messaging: ^14.9.1
  firebase_storage: ^11.7.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_facebook_auth: ^6.2.0
  flutter_native_splash: ^2.4.0
  flutter_otp_text_field: ^1.1.3+2
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  get_it: ^7.7.0
  google_sign_in: ^6.2.1
  image_picker: ^1.1.0
  internet_connection_checker: ^1.0.0+1
  mockito: ^5.4.4
  persistent_bottom_nav_bar: ^5.0.2
  shared_preferences: ^2.2.3
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/png/
    - assets/images/svg/

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/Urbanist-VariableFont_wght.ttf
