// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWsRDYfWgwG-0BlwKsnpkWiuJexd0d5YY',
    appId: '1:6028053348:web:a590a07a7c5818925b0871',
    messagingSenderId: '6028053348',
    projectId: 'zuzu-ef479',
    authDomain: 'zuzu-ef479.firebaseapp.com',
    storageBucket: 'zuzu-ef479.appspot.com',
    measurementId: 'G-QZ1CK6S91H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz1gPdOxHPH7QvUzssp-TAeFc3zD2UsrM',
    appId: '1:6028053348:android:9622bc1399136fb65b0871',
    messagingSenderId: '6028053348',
    projectId: 'zuzu-ef479',
    storageBucket: 'zuzu-ef479.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI6grICUmxM-DvVIXBIXSJwgyYsUjptHk',
    appId: '1:6028053348:ios:a874afcdef5ee5675b0871',
    messagingSenderId: '6028053348',
    projectId: 'zuzu-ef479',
    storageBucket: 'zuzu-ef479.appspot.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI6grICUmxM-DvVIXBIXSJwgyYsUjptHk',
    appId: '1:6028053348:ios:31cbcfba9c1630c35b0871',
    messagingSenderId: '6028053348',
    projectId: 'zuzu-ef479',
    storageBucket: 'zuzu-ef479.appspot.com',
    iosBundleId: 'com.example.socialMediaApp.RunnerTests',
  );
}
